### ISSUE TITLE
Error while trying to add the package to meteor in windows

### ISSUE THREAD

**Issue by shaunthomas999** [fourseven/meteor-scss#87] opened 2015-05-18 23:09 UTC
Hi,

I got the following error while trying to add the package to meteor in my windows machine;
meteor add fourseven:scss
=> Errors while adding packages:

While checking for fourseven:scss@3.0.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform. 

Any suggestion for solving the problem?

**Comment by fourseven** [comment] 2015-05-19 03:43
This is a duplicate of #83 – I need to release 3.1.1 which should fix this.

**Closed by fourseven** 2015-05-19 03:43 UTC

**Comment by shaunthomas999** [comment] 2015-05-20 10:32
Ok. Thank you!

**Comment by fourseven** [comment] 2015-05-20 10:33
It was released btw, so give 3.1.1 a go :+1:

**Comment by shaunthomas999** [comment] 2015-05-20 10:50
Just tried it. Itz a go :+1:
