### ISSUE TITLE
Error after 'meteor update' - no compatible binary found

### ISSUE THREAD

**Issue by palpinter** [fourseven/meteor-scss#201] opened 2016-08-07 09:33 UTC
Hi,

I've received this error message after "meteor update":

`
This project is already at Meteor 1.4.0.1, the latest release.
=> Errors while upgrading packages:           
                                              
While checking for fourseven:scss@3.8.1:
error: No compatible binary build found for this package. Contact the package author and ask them to
publish it for your platform.
`

In the ".meteor/versions":
`fourseven:scss@3.8.0_1`

any idea?

Thx Pal

**Comment by sebakerckhof** [comment] 2016-08-07 09:34
I just released a new version, but the binaries still need to be build. Try again in a few minutes.

**Comment by sebakerckhof** [comment] 2016-08-07 10:34
https://github.com/meteor/meteor/issues/7599

**Comment by NitroBAY** [comment] 2016-08-07 17:56
The problem is still there 8 hours later.

**Comment by sebakerckhof** [comment] 2016-08-07 19:19
Yep. Meteor build servers are failing on me. See referenced issue

**Comment by cleandersonlobo** [comment] 2016-08-07 20:05
+1

**Comment by cdcv** [comment] 2016-08-07 20:47
+1

**Comment by cdcv** [comment] 2016-08-07 21:12
Is there a workaround in the meantime?  We need to get the upgrade to work asap. Thanks very much for your help.

**Comment by Ben305** [comment] 2016-08-07 21:56
Just pin the version with `@=3.8.0_1`

**Comment by cdcv** [comment] 2016-08-07 22:08
Thanks for your help.  Had already tried that.  Would you mind being more specific on exactly how to do that?  We already had that version set, but still got the issue above when we tried to Meteor Update.  Thanks again.

**Comment by fabyeah** [comment] 2016-08-08 01:03
@cdcv I removed fourseven:scss@3.8.0_1 from .meteor/versions and it was added again when running meteor and it worked.

**Comment by R0binT** [comment] 2016-08-08 07:51
+1

**Comment by prawee** [comment] 2016-08-08 08:15
+1

**Comment by Ben305** [comment] 2016-08-08 08:19
Just update `fourseven:scss` to `fourseven:scss@=3.8.0_1` in your package-file in the `.meteor` directory to pin the version.

**Comment by thearabbit** [comment] 2016-08-08 09:12
Still the same problem with `fourseven:scss@=3.8.0_1`
+1

**Comment by c9s** [comment] 2016-08-08 09:47
Same here .......

**Comment by c9s** [comment] 2016-08-08 09:47
`fourseven:scss@=3.8.0_1` doesn't work. Travis-CI build failed.

**Comment by NitroBAY** [comment] 2016-08-08 10:57
3.8.0_1 doesn't work

**Comment by danimbrogno** [comment] 2016-08-08 15:57
+1

**Comment by danimbrogno** [comment] 2016-08-08 15:59
Running `meteor add fourseven:scss@=3.8.0_1` in console did not work, however, adding the line:`fourseven:scss@=3.8.0_1` directly to the .meteor/packages file worked.

**Comment by c9s** [comment] 2016-08-08 16:05
For people who encountered error, you can use `c9s:scss` to get the binary package.

**Comment by TristanWiley** [comment] 2016-08-08 22:20
Doing as @danimbrogno suggested worked for me, replacing the current package in .meteor/packages to `fourseven:scss@=3.8.0_1` worked.

**Comment by exequiel09** [comment] 2016-08-08 23:16
Downloading fourseven:scss@3.8.1..  Works now on my machine!

**Comment by exequiel09** [comment] 2016-08-08 23:17
Downloading fourseven:scss@3.8.1.. Works now on my machine!

**Comment by tarunbatra** [comment] 2016-08-09 11:13
I can confirm pinning the package to `1.3.8.0_1` works, but not `3.8.1`

**Comment by exequiel09** [comment] 2016-08-09 11:18
Can confirm this 3.8.1 on my machine.

![screen shot 2016-08-09 at 7 19 12 pm](https://cloud.githubusercontent.com/assets/1289472/17514594/0b59b390-5e66-11e6-8ee7-36315421b4b2.png)

**Comment by sebakerckhof** [comment] 2016-08-09 11:36
I've been able to publish it for win and mac, but not yet for linux...

**Comment by sturoid** [comment] 2016-08-09 18:04
@sebakerckhof I'm guessing the linux binary would fix pushing to Heroku. Is that correct?

**Comment by sebakerckhof** [comment] 2016-08-09 18:07
Yes, if your deployment on heroku worked before and has now stopped it's because of the missing linux binaries. Still trying to publish the build, but the meteor build servers shut down before the build completes...

**Comment by serkandurusoy** [comment] 2016-08-10 13:32
@sebakerckhof do you know if there is a place where we can check to see if the linux binary is also built and published (without actually trying to upgrade or deploy on heroku without a version constraint)?

**Comment by sebakerckhof** [comment] 2016-08-10 14:03
@serkandurusoy don't know of such a place. At least not an easy one.
You could check out the sqlite database meteor keeps on your hard drive containing all package information: `meteor-installation/package-metadata/v2.0.1/packages.data.db`. It has a table `builds`, wouldn't be too hard to write a script that tells you this info. 

Anyway, in this particular instance I'll make a comment here when the build has finally succeeded.

**Comment by serkandurusoy** [comment] 2016-08-10 14:19
Is there anything we can do for you to help build? I am using an ubuntu 64bit laptop, can I create the build for you, for example?

**Comment by fourseven** [comment] 2016-08-11 05:36
We're still fighting the build boxes - https://github.com/meteor/meteor/issues/7599#issuecomment-239077318

@serkandurusoy short answer is no, we need the meteor build boxes because they're configured to be the lowest common version of linux/macos/windows that meteor supports, so there's more guarantees that the binaries they build will run on all meteor installs.

**Comment by Nico-L** [comment] 2016-08-11 07:29
Hi,

I have the very same problem after a clean re install of an existing app. Neither the 3.8.0_1 or the 3.8.1 versions is working. I am stuck. Does any temporary workaround exist? Is there the possibility to downgrade further to make sure at least a basic working?

**Comment by sebakerckhof** [comment] 2016-08-11 07:39
problem is that 3.8.1 is the only one which would work with meteor 1.4. Only workaround for now that I can think of is cloning this package locally in the packages folder of your application

**Comment by serkandurusoy** [comment] 2016-08-11 07:53
Do we have no way that we can create a linux box that's spec-compliant with
the meteor build boxes? How hard can it be? It is linux after all! There
are just a handful of build dependencies for node binary builds and they
are all standard on package repos.

A fresh ubuntu 14.04 or 16.04 install with  apt update && apt upgrade &&
apt install git curl build-essential will give us everything we need!

**Comment by rohanray** [comment] 2016-08-12 06:51
Hi @sebakerckhof any update on the state of linux build for v 3.8.1?

Thanks,
Rohan.

**Comment by sebakerckhof** [comment] 2016-08-12 07:24
@rohanray Nope, no progress... What you can do for now is clone the package in your local packages folder of your project. And when meteor 1.4.1 is released (should be soon) I can publish a version which does not need a binary build by the package author anymore ( https://github.com/meteor/meteor/pull/7608 )

**Comment by rohanray** [comment] 2016-08-12 09:33
@sebakerckhof Thanks for the update! It's a really good news for 1.4.1+ I can live with a locally cloned package till then.

**Comment by RaymondLC92** [comment] 2016-08-13 03:30
Do we have any timeframe on when this will be fixed?

Is there nothing we can do prior to meteor 1.4.1? (I know you mentioned cloning the package in your local packages folder but I'm not sure what you mean by that)

Thanks for the great package and your time.

**Comment by rohanray** [comment] 2016-08-13 06:38
@RaymondLC92 There are 2 alternatives prior to Meteor 1.4.1

1. pin the package to 3.8.0_1 in packages.
Edit packages file inside .meteor folder from `fourseven:scss` to `fourseven:scss@=3.8.0_1`
Option 1 worked for me

2. clone the package
If you don't have a folder named `packages` inside your meteor root project directory, create `packages` folder. 
Then using your terminal cd inside packages directory. e.g. `cd <meteor-proj>/packages`
Then execute the command : `git clone https://github.com/fourseven/meteor-scss.git`
Then inside meteor-project directory i.e. `cd ..` after previous command, execute `meteor reset` and then `meteor`

It should work

**Comment by RaymondLC92** [comment] 2016-08-13 06:43
@rohanray 

I actually already fixed it with option 2, it took a bit of googling to find out what he meant by local packages but I got it. I ended up setting a PACKAGE_DIRS environment variable I'm not fully convinced was necessary though.

Thanks for the help regardless, now I just have to find out why susy isn't working.

**Comment by ansaries** [comment] 2016-08-18 07:58
While checking for fourseven:scss@3.8.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

I am running bash on Ubuntu on Windows. And I think @sebakerckhof  has already updated the binaries for Windows and Mac, but have you done for Linux also?


looking forward...

**Comment by WayneUong** [comment] 2016-08-18 23:45
```
While checking for fourseven:scss@3.8.1:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.

```
I'm using mupx to build and deploy on Ubuntu. App works fine locally on OSX.

**Comment by iameli** [comment] 2016-08-19 01:10
1.4.1 is out, can this be fixed now?

**Comment by iameli** [comment] 2016-08-19 01:51
I went ahead and published `csats:scss@3.8.1`, and it appears to be working on both Linux and macOS.

**Comment by mafzst** [comment] 2016-08-19 12:57
@iameli Nope :( Even with Meteor 1.4.1 I've the problem. Wait and see...

**Comment by mitar** [comment] 2016-08-20 07:52
> do you know if there is a place where we can check to see if the linux binary is also built and published (without actually trying to upgrade or deploy on heroku without a version constraint)?

Yes, you can do:

```
meteor show --ejson fourseven:scss
```

And you will see something like this in the output:

```
  "architecturesOS": [
    "os.windows.x86_32",
    "os.osx.x86_64"
  ]
```

Other versions have four entries.

**Comment by mitar** [comment] 2016-08-20 07:55
> What you can do for now is clone the package in your local packages folder of your project.

It does not really work: https://github.com/meteor/meteor/issues/7675

**Comment by smtx** [comment] 2016-08-22 00:11
In .meteor/versions change the package with fourseven:scss@3.8.0_1

It works for me on heroku

**Comment by sebakerckhof** [comment] 2016-08-22 12:56
Version 3.9.0 has been published using the new method in meteor 1.4.1, that no longer requires pre-build binaries.

**Comment by mafzst** [comment] 2016-08-22 13:06
@sebakerckhof It's working for me :tada: Thanks a lot !

**Comment by mitar** [comment] 2016-08-22 17:37
For me as well on CircleCI. Tests are finally working again!

**Closed** 2016-08-23 14:10 UTC

**Comment by devagrawal09** [comment] 2017-08-28 09:03
Still doesnt work on windows
