### ISSUE TITLE
Import each scss file only once

### ISSUE THREAD

**Issue by stuhlmueller** [fourseven/meteor-scss#168] opened 2016-02-24 18:21 UTC
Is there a way to enforce that each scss file is imported only once? For example, can the [import-once](https://github.com/Compass/compass/tree/master/import-once) plugin be used with `meteor-scss`?

**Comment by s7dhansh** [comment] 2016-04-11 07:15
+1. Has become urgent mostly because of Meteor 1.3 imports.

**Comment by sebakerckhof** [comment] 2016-04-11 12:25
@s7dhansh 
What's the exact error you see? 

Can you copy-paste the import statements you use in main.scss?

**Comment by s7dhansh** [comment] 2016-04-11 12:57
@sebakerckhof

On digging further I realized that the problem is something else. The files in "imports" are getting compiled (unless they are prefixed with `_`) and hence the errors are thrown.

Reproduction: https://github.com/s7dhansh/meteor-scss-problem - problem branch contains style.scss while master contains _style.scss

**Comment by sebakerckhof** [comment] 2016-04-11 18:05
@s7dhansh okay, I thought Meteor-tool would automatically recognize files in the imports directory as imports, but I had to specify this manually for 1.3. 
It should be fixed but I'll need to wait for @fourseven to update to Atmosphere.
You could run a local version in the meanwhile.

**Comment by fourseven** [comment] 2016-04-11 23:02
Just finishing the publish-for-arch now. @sebakerckhof, you're doing an amazing job here, I've just added you as an admin to this package, so releases aren't tied to me.

**Comment by s7dhansh** [comment] 2016-04-12 06:41
Thank you! Kudos @sebakerckhof and @fourseven . Good decision too ! :+1:

**Comment by s7dhansh** [comment] 2016-04-12 07:05
@stuhlmueller should we close this? you can structure your app in a meteor 1.3 way to avoid import-once.

**Comment by sebakerckhof** [comment] 2016-04-14 17:33
thanks @fourseven.
@stuhlmueller To answer the original question, there's currently no such way. `fourseven:scss` is based on node-sass/libsass and the import-once plugin is for the (less and less used) ruby version of sass.

Basically, like @s7dhansh says, a good directory structure can enforce this.

**Closed by sebakerckhof** 2016-04-14 17:33 UTC

**Comment by sebakerckhof** [comment] 2016-04-15 16:02
@s7dhansh : Just a heads up. After this discussion: https://github.com/meteor/meteor/commit/cd8bc10b1d7be519d43ec92c612e738ca091a311 I'm going to undo the change. The rationale can be found in the discussion. Basically, in Meteor 1.3.2 you will not get errors anymore and you will be able to include scss from javascript if you put them in the imports directory.

**Comment by s7dhansh** [comment] 2016-04-16 01:45
Oh that would be awesome! Scss from js. Perfect.

On Fri, Apr 15, 2016, 9:32 PM Seba Kerckhof <notifications@github.com>
wrote:

> @s7dhansh <https://github.com/s7dhansh> : Just a heads up. After this
> discussion: meteor/meteor@cd8bc10
> <https://github.com/meteor/meteor/commit/cd8bc10b1d7be519d43ec92c612e738ca091a311>
> I'm going to undo the change. The rationale can be found in the discussion.
> Basically, in Meteor 1.3.2 you will not get errors anymore and you will be
> able to include scss from javascript if you put them in the imports
> directory.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/fourseven/meteor-scss/issues/168#issuecomment-210521464>
>
-- 
Sudhanshu
