### ISSUE TITLE
File to import: not found - Meteor 1.2 , 3.3.x version

### ISSUE THREAD

**Issue by kristijanhusak** [fourseven/meteor-scss#122] opened 2015-10-01 07:34 UTC
Hi,

I'm not sure if this is a duplicate of https://github.com/fourseven/meteor-scss/issues/118 , but i'm having the similar issue with new versions on Meteor 1.2.

```
   While processing files with fourseven:scss (for target web.browser):
   /scss/screen.scss: Scss compiler error: File to import: ../.meteor/local/bower/inuit-defaults/settings.defaults
   not found. Import origin: /scss/screen.scss

```

For some reason, file is not found, but it exists.

When i downgrade to 3.1.1, it works fine.

**Comment by sebakerckhof** [comment] 2015-10-01 08:00
This is different from #118 . However, the problem is that these files are not being tracked by Meteor.

We could maybe check if the file exists if Meteor does not track it. But I first want to focus on #118, since it will require some rewrites

**Comment by kristijanhusak** [comment] 2015-10-01 10:50
No problem, older version works fine. Just let me know when there is some progress on this. Thanks.

**Comment by sebakerckhof** [comment] 2015-10-01 14:45
Closing this in favor of #124

**Closed by sebakerckhof** 2015-10-01 14:45 UTC
