### ISSUE TITLE
Importing css files

### ISSUE THREAD

**Issue by schmidsi** [fourseven/meteor-scss#219] opened 2016-09-01 16:17 UTC
It does not import css files but scss files. There is this error:

```
While processing files with fourseven:scss (for target web.browser):
   /client/main.scss: Scss compiler error: File to import: {}/imports/ui/style/fonts/brandon.css not found in file:
   ../imports/ui/style/app.scss
```

If I rename this file to `brandon.scss` and import it accordingly, it works. Is this by purpose or a bug? Any hint where I can try to fix it by myself and make a pull request?

Would be great to import styles from other packages, which are not scss.

**Comment by sebakerckhof** [comment] 2016-09-13 18:21
This should work.
Logic should be somewhere in the `getRealImportPath` function: https://github.com/fourseven/meteor-scss/blob/master/plugin/compile-scss.js#L104

**Comment by macrozone** [comment] 2016-09-20 11:23
I also confirm that this does NOT work.

**Comment by yanickrochon** [comment] 2016-10-04 21:28
Because a  picture is worth a thousand words

![selection_099](https://cloud.githubusercontent.com/assets/78461/19093101/c56ec276-8a57-11e6-8d1d-2013c9a0d897.png)

**Comment by sebakerckhof** [comment] 2016-10-18 22:10
@yanickrochon I believe your bug is actually another one which I plan to tackle soon: https://github.com/fourseven/meteor-scss/issues/195

**Comment by datanotion** [comment] 2016-11-09 21:48
@yanickrochon did you find a workaround for this?  Trying to upgrade to Meteor 1.4 today from 1.3 and we are suddenly getting this error.  Thx.

**Comment by yanickrochon** [comment] 2016-11-09 22:05
@datanotion Unfortunately, not exactly. However, Meteor does support loading CSS directly from any module, so

```js
import 'react-image-crop/dist/ReactCrop.css';
```

works. It won't work with SCSS, but npm modules usually are published with a compiled CSS. If the SCSS is in your own project, [Meteor SCSS module](https://github.com/fourseven/meteor-scss) will compile it and merge it automatically; this issue only concerns importing npm modules' SCSS files.

**Comment by sebakerckhof** [comment] 2017-02-17 18:31
Closing, as duplicate of: https://github.com/fourseven/meteor-scss/issues/195

**Closed by sebakerckhof** 2017-02-17 18:31 UTC

**Comment by pilarArr** [comment] 2017-07-13 12:52
I have this problem with v4.5.4, I try to import a `.css` file and I can't unless I change the extension to `.scss`. 

I have a stylesheets folder with `app.scss` and the `.css` file is in the same folder.
