### ISSUE TITLE
Compilation failed while node-sass works !

### ISSUE THREAD

**Issue by gaillota** [fourseven/meteor-scss#217] opened 2016-08-23 19:12 UTC
Hi,

I'm trying to use the CSS framework Bulma on my projet, but I want to customize the variables.
What I did was
`npm install bulma`
Create a `client/main.scss` file and put in it:
```
// Custom variables
$custom-var: 'custom-value;

// Bulma stylesheets
@import '{}/node_modules/bulma/bulma';
```

The problem is that I get this error when it's compiled:
```
While` processing files with fourseven:scss (for target web.browser):
   /client/main.scss: Scss compiler error: Invalid CSS after "@charset":
   expected 1 selector or at-rule, was '"utf-8"'
```

But when I `npm install node-sass` and run `node-sass --include-path node_modules client/main.scss public/stylesheets/style.css` (also changing the path of bulma sass file), it works.

I'm guessing the error doesn't give any clue on why it doesn't work, it's just the first line of the `bulma.sass` file.

Any ideas on why the compilation through the package doesn't work ?

**Comment by ecsnavarretemit** [comment] 2016-09-04 04:39
@gaillota this is related to #120 i think since bulma uses the SASS indented syntax, the one with .sass extension.

**Comment by exequiel09** [comment] 2016-09-04 04:41
@gaillota i think this is related to #120. Since bulma uses the SASS indented syntax, the one with .sass extension

**Comment by sebakerckhof** [comment] 2016-10-04 21:28
Yep, duplicate of https://github.com/fourseven/meteor-scss/issues/120

See discussion there as to why this can not be fixed ATM (waiting for fix in node-sass)

**Closed by sebakerckhof** 2016-10-04 21:28 UTC

**Comment by gaillota** [comment] 2016-10-05 13:22
Ok, thank you guys for the reply.
