### ISSUE TITLE
nested imports with same filenames are ignored

### ISSUE THREAD

**Issue by chris74656** [fourseven/meteor-scss#183] opened 2016-06-21 08:16 UTC
let's assume following file structure:

**/style1/main.scss**
**/style1/_content.scss**

**/style2/main.scss**
**/style2/_content.scss**

where:
**/style1/main.scss** imports **/style1/_content.scss**
and
**/style2/main.scss** imports **/style2/_content.scss**

now when **/style1/main.scss** is imported in **/style2/main.scss** the second content file **/style2/_content.scss** is completely ignored.
No css rules get applied, no errors occour, even if i add some intentional invalid lines to **/style2/_content.scss** there are no errors shown in the console during transpiling.

The problem can be resolved by renaming **/style2/_content.scss** to something like **/style2/_someOtherContent.scss**

this may be an edge case or even be intended behavior by the transpiler but neither the less i think it should at least be noted.

**Comment by sebakerckhof** [comment] 2016-06-21 08:20
This is a known issue (duplicate of: https://github.com/fourseven/meteor-scss/issues/174 ).
Basically node-sass doesn't give us enough information. We can't give a warning since we simply don't know about it.

Luckily it's an edge case that not a lot of users will experience.

**Comment by sebakerckhof** [comment] 2016-06-21 08:22
I'll close this since it would require a change in node-sass, which is not likely to happen: https://github.com/sass/node-sass/issues/1188

**Closed by sebakerckhof** 2016-06-21 08:22 UTC

**Comment by gregorybleiker** [comment] 2016-09-15 05:39
Well its an edge case that stops react-toolbox from working...
