### ISSUE TITLE
Error after updating to latest release 3.3.3_1

### ISSUE THREAD

**Issue by dr-dimitru** [fourseven/meteor-scss#117] opened 2015-09-30 06:41 UTC
I've got this error: `Scss compiler error: top-level directive must be terminated by ';'`
After updating to `3.3.3_1`, I guess `_1` prefix for unstable, but I decide to let you know

__UPD:__ Same issue on `v3.3.3` and `v3.2.0` to `v2.1.1` (which perfectly works)

**Comment by sebakerckhof** [comment] 2015-09-30 06:48
Can you provide a reproduction.

**Comment by dr-dimitru** [comment] 2015-09-30 06:54
@sebakerckhof yes, I have file `main.sass`:
```sass
.well
  padding: 10px 7px
  margin: 10px 0px

.well-sm
  padding: 7px 5px
  margin: 0px auto 7px auto
```

With or without file `scss.json`:
```json
{
  "enableAutoprefixer": true
}
```
I don't have any `@import`s or comments in a file.

BTW sometimes it shows `Scss compiler error: invalid top-level expression` error somewhy..

Full error stack:
```shell
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While processing files with fourseven:scss (for target web.browser):
   /client/main.sass: Scss compiler error: invalid top-level expression
   
   
=> Your application has errors. Waiting for file change.
```

**Comment by dcworldwide** [comment] 2015-09-30 07:00
I'm also experiencing similiar errors since upgrading to 3.3.3_1.

```
While processing files with fourseven:scss (for target web.browser):
   /client/style/uploadcare/uploadcare.sass: Scss compiler error: invalid top-level expression
   
   /client/style/emoji.sass: Scss compiler error: invalid top-level expression
   
   /client/style/flickity.sass: Scss compiler error: invalid top-level expression
```

I've tried removing my index.scss and allowing the package to re-create it (however it does not).

**Comment by sebakerckhof** [comment] 2015-09-30 07:28
3.3.3 is a complete rewrite for the new meteor build system in version 1.2. It currently does not support autoprefixing and generation of index files.

Anyway, I believe the sass compiler thinks it is scss instead of sass syntax. I don't know if I can hint the compiler so it knows the syntax.

**Comment by dr-dimitru** [comment] 2015-09-30 07:32
@sebakerckhof Any idea how to fix it right now?

**Comment by sebakerckhof** [comment] 2015-09-30 07:39
You could try downgrading to 3.3.2, by specifying 'fourseven:scss@3.3.2' in your package imports

**Comment by Narven** [comment] 2015-09-30 09:46
I've tested and I'm having those problems with `3.3.3` and `3.3.3_1`. Not with `3.2.0`

The errors showing are:

```
While processing files with fourseven:scss (for target web.browser):
   /client/stylesheets/theme_0.sass: Scss compiler error: top-level @import directive must be terminated by ';'
```

```
While processing files with fourseven:scss (for target web.browser):
   /client/stylesheets/theme_0.sass: Scss compiler error: @import directive requires a url or quoted path
```

**Comment by sebakerckhof** [comment] 2015-09-30 09:52
yeah, I got a fix ready.

2015-09-30 11:46 GMT+02:00 Narven <notifications@github.com>:

**Comment by sebakerckhof** [comment] 2015-09-30 10:00
I pushed some changes, Can you guys test locally with the master branch of this repo.

**Comment by Narven** [comment] 2015-09-30 10:10
On `3.3.3_1` still getting:

```
/client/stylesheets/theme_0.sass: Scss compiler error: top-level @import directive must be terminated by ';'
```

**Comment by sebakerckhof** [comment] 2015-09-30 10:22
Are you sure Meteor is using the local package you cloned from the master?

**Comment by dr-dimitru** [comment] 2015-09-30 10:24
@Narven @sebakerckhof I usually increment version of local package to see "update message" at console to make sure I'm using the local one

**Comment by dr-dimitru** [comment] 2015-09-30 10:29
Fixed on my end. 
But - I don't use `@import`s and/or comments

**Comment by Narven** [comment] 2015-09-30 10:32
@sebakerckhof dont know for sure... or even if atmosphere is caching the previous 3.3.3_1.

[https://atmospherejs.com/fourseven/scss](https://atmospherejs.com/fourseven/scss) says that the last is from yesterday (29 set)

**Comment by keithn** [comment] 2015-09-30 10:52
just updated to your master branch.... the errors like people were getting above are gone, and now I get 
![image](https://cloud.githubusercontent.com/assets/86080/10191178/3691abce-67ce-11e5-8695-197bc3405dc7.png)

running Win10

**Comment by dr-dimitru** [comment] 2015-09-30 10:57
@sebakerckhof @Narven @keithn the commit https://github.com/fourseven/meteor-scss/commit/ca6580f2f46478362b1bd77903fa5af4c96054ca is fixed those error on my end. Make sure you are cloning rep including this commit

**Comment by keithn** [comment] 2015-09-30 11:01
I have the code in that commit....

**Comment by keithn** [comment] 2015-09-30 11:31
I have an import ( that used to work before upgrading )   @import client/css/custom.sass

I changed the code (comile-scss) to to console.log...   
![image](https://cloud.githubusercontent.com/assets/86080/10191773/8a42ed28-67d3-11e5-8ac1-1ee4a13514ac.png)
and my paths get translated to 

![image](https://cloud.githubusercontent.com/assets/86080/10191792/aba63600-67d3-11e5-92ae-b5a1359e67e7.png)

seems to prepend and extra "client" onto the path?

**Comment by sebakerckhof** [comment] 2015-09-30 11:57
@keithn This seems correct to me.
client/css/custom.sass is relative to client/categories_list.sass, So it prepends the current directory (client)

**Comment by sebakerckhof** [comment] 2015-09-30 12:02
Edit: The less package would give the same error with a similar directory structure.

**Comment by sebakerckhof** [comment] 2015-09-30 12:04
I'll close this issue since it is related to .sass files and not to import directories.

**Closed** 2015-09-30 12:04 UTC
Labels: bug

**Comment by keithn** [comment] 2015-09-30 20:24
only thing is, that's not how it was working in the previous version,  it would load take the path from the root.

**Comment by dr-dimitru** [comment] 2015-10-01 00:50
@keithn So its major release then.
@sebakerckhof could you please let us know when current release will be published?

**Comment by fourseven** [comment] 2015-10-01 07:05
Released!

**Comment by brunolemos** [comment] 2015-10-01 07:38
Still having the same problem on 3.3.3_2

**Comment by fourseven** [comment] 2015-10-01 07:50
:cry: and `3.3.3_3`? (messed up that last release)

**Comment by brunolemos** [comment] 2015-10-01 07:54
````
/client/templates/components/header/header.sass: Scss compiler error: top-level variable binding must be
   terminated by ';'
````

**Comment by dr-dimitru** [comment] 2015-10-01 08:35
@sebakerckhof I didn't noticed yesterday, but auto-prefixing doesn't work anymore :(

**Comment by sebakerckhof** [comment] 2015-10-01 08:49
It's not included in this release, see the readme.

**Comment by mikeifomin** [comment] 2015-10-01 09:42
It doesn't  work for in my project. still... 

```
/client/inc/headerProfile.scss: Scss compiler error: File to import: vars
   not found. Import origin: /client/inc/headerProfile.scss
   
   While minifying app stylesheet:
   app/style.css:253:29: property missing ':'
```

in /client/inc/headerProfile.scss file
```
@import "../stylesheets/vars.scss";
```

**Comment by mikeifomin** [comment] 2015-10-01 14:04
I've downgraded to 3.1.1 Everything is ok.

**Comment by rista404** [comment] 2015-10-01 16:59
I'm having similar issues with 3.3.3_3 version.

```
While processing files with fourseven:scss (for target web.browser):
/client/stylesheets/style.sass: Scss compiler error: @import directive requires a url or quoted path
```

The file looks like this:
```sass
@import include/all
@import partials/all
@import layouts/all
```

**Comment by Narven** [comment] 2015-10-01 17:43
@mikeifomin 3.2.0 should be ok. at least 3.2.0 is working for me with no issues

**Comment by luisreyes** [comment] 2015-10-02 15:49
I was having the same issue and after a while realized that I had an **empty .scss file**. This was making the compiler to fail.

**Comment by mikeifomin** [comment] 2015-10-03 19:32
@Narven  You're right! I'm a little reinsured)

**Comment by dr-dimitru** [comment] 2015-10-03 22:41
@Narven including auto-prefixing?

**Comment by Narven** [comment] 2015-10-03 22:44
Im not sure about auto-prefixing. I dont care about other browsers. what I do is only for one browser.

**Comment by rista404** [comment] 2015-12-11 20:55
Bump, still the same problem with `fourseven:scss@3.4.1`  
```
Scss compiler error: @import directive requires a url or quoted path
```

**Comment by dr-dimitru** [comment] 2015-12-12 03:30
@rista404 I'm happy with `v2.1.1`.
