### ISSUE TITLE
Importing files of subfolders with same relative-path won't work.

### ISSUE THREAD

**Issue by MiMaMuh** [fourseven/meteor-scss#227] opened 2016-10-17 11:20 UTC
Hi, it seems there is an issue in `3.10.0` when I try to import scss files from subfolder which create identical relative path structures:

Example:
Each directory has its own `scss file` wich `imports` the scss-files of its sub-directories:
```
main.scss                     // imports ./subdir1/comp-styles.scss and ./subdir2/comp.styles-scss
    subdir1
        comp-styles.scss      // imports ./comps/styles.scss
        comps
            styles.scss       // imports comp-1.scss and comp-2.scss
            comp-1.scss       // css: .comp-1 { ... }
            comp-2.scss       // css: .comp-2 { ... }
    subdir2
        comp-styles.scss      // imports ./comps/styles.scss
        comps
            styles.scss       // imports comp-3.scss
            comp-3.scss       // css: .comp-3 { ... }
```
It seems, as long as the two files `comp-styles.scss` has the same import statement with the same relative path `@import './comps/styles.scss'` the output of `main.scss` will be wrong. Instead of:

```css
.comp-1 { ... }
.comp-2 { ... }
.comp-3 { ... }
```
it will output the values of `subdir1/comp-styles.scss` for `subdir2/comp-styles.scss`:
```css
.comp-1 { ... }
.comp-2 { ... }
.comp-1 { ... } // instad of .comp-3 { ... } we get the output of subdir1/comp-styles.scss again
.comp-2 { ... }
```

To prevent this behaviour, I have to prevent that the two files `comp-styles.scss` have the same import statement `@import './comps/styles.scss'`. 

So there would be three options/workarounds:
1. Remove `styles.scss` as import-step and import the `comp-x.scss` files directly in `comp-styles.scss`.
2. Or rename the `comps` folder in `comps1, comps2, ...`;
3. Or finally rename the `styles.scss` files in `styles-1.scss, styles-2.scss, ...`

I've tried to fix the issue but I can't figure it out where it comes from.

**Comment by sebakerckhof** [comment] 2016-10-17 17:57
Duplicate of: https://github.com/fourseven/meteor-scss/issues/174 which has some more information

Basically, node-sass doesn't give us enough information to identify which file is meant.

**Closed by sebakerckhof** 2016-10-17 17:57 UTC
