### ISSUE TITLE
@import .sass files problem

### ISSUE THREAD

**Issue by mikeifomin** [fourseven/meteor-scss#156] opened 2015-11-11 17:29 UTC
I have simple structure with  style.sass and _variables.sass files in the same level

``` sass
// style.sass
@import variables

// _variables.sass
$var1:  10
$var2:  20
```
And it cause "Scss compiler error"

### Dig dipper

When import in [your code](https://github.com/fourseven/meteor-scss/blob/master/plugin/compile-scss.js#L179) 

``` javascript
const importer = function(url,prev,done){
     ...
     done({ contents: allFiles.get(parsed.path).getContentsAsString()});
}
...
const options = {
    ...
    importer: importer
}
...
sass.render(options,f.resolver());

``` 

[importer](https://github.com/sass/node-sass#importer--v200---experimental) in node-sass get `contents` but only in scss format (not **sass**)

**Comment by sebakerckhof** [comment] 2015-11-11 17:31
Duplicate of #120

**Closed by sebakerckhof** 2015-11-11 17:31 UTC
