### ISSUE TITLE
Meteor 1.2 scss 3.3.3 and subimports

### ISSUE THREAD

**Issue by juliancwirko** [fourseven/meteor-scss#118] opened 2015-09-30 08:29 UTC
Hey, I have a problem with Foundation 5 
I need to be able to use new syntax: 
For example in the main apps scss file I want to import components:
```
@import {juliancwirko:zf5}/scss/foundation/components/grid.scss
```
and it works well but there is another import in grid.scss which I shouldn't import by hand in the main scss file:
```
@import 'global'
```
global.scss is on the same folder level (in the package) so it should be visible for the build plugin. I am not sure but I think that it works well in Stylus and probably in Less build plugins. 
 
Also I have included all scss files from the package in the package.js file on the client, but in the main app scss file I import only main components files without subimports. This is how it should work.

After all I get an error:
```
While processing files with fourseven:scss (for target web.browser):
   /client/stylesheets/main.scss: Scss compiler error: File to import: global not found. Import origin: /client/stylesheets/main.scss
```

I will try to look into new build plugin later, but maybe someone have a quick answer for that. Thanks.

**Comment by sebakerckhof** [comment] 2015-09-30 10:08
Hmm, for some reason it thinks the import is in client/stylesheets/main.scss, so it searches for the file relative to client/stylesheets/main.scss instead of the grid.scss location.

However, I've tested this scenario here: https://github.com/sebakerckhof/meteor-scss-test and there it works. 

Needs further investigation.

**Comment by juliancwirko** [comment] 2015-09-30 10:14
cool, thanks! 
I will look into it too, as soon as I'll find some more time :)

**Comment by sebakerckhof** [comment] 2015-09-30 12:05
The isImport flag is new in meteor 1.2, but in fact it should not matter if the file is prefixed with an underscore.

**Comment by sebakerckhof** [comment] 2015-09-30 12:35
Okay, I know what's wrong. I think I know how to fix it too.

**Comment by sebakerckhof** [comment] 2015-09-30 16:25
okay, I had a quick look (kind of busy with other stuff). I think we could use the prev variable we get in the sass importer to calculate the correct path. We'd have to join all paths and reset whenever we get a new absolute path. However, I don't know how we'd calculate the correct source map url. Maybe we should keep a mapping per inputfile.

**Comment by sebakerckhof** [comment] 2015-10-01 11:43
Okay, the problem is related to node-sass ( https://github.com/sass/node-sass/issues/1188 ) , but fixed in the next beta. I'll have to rewrite some stuff myself thoug.

**Comment by juliancwirko** [comment] 2015-10-01 12:14
Ok, thanks. So this something bigger than I thought :/

**Comment by sebakerckhof** [comment] 2015-10-01 13:52
Yeah, the problem is that the importer plugin functionality of sass doesn't provide you with as much information as the ones from stylus and less + it went through the import tree in a weird fashion.

Anyway, could you try this fork locally: https://github.com/sebakerckhof/meteor-scss and let me know if everything works for you now.

**Comment by juliancwirko** [comment] 2015-10-01 14:11
Yeah! :) It seems to work with your fork.

**Closed** 2015-10-01 14:31 UTC
Labels: bug

**Comment by juliancwirko** [comment] 2015-10-01 15:30
Version from master works now, but it seems that there is an old code on Atmosphere. 
Could you publish it on Atmosphere?

**Comment by sebakerckhof** [comment] 2015-10-01 15:34
I can't do that, @fourseven will have to do this.

**Comment by fourseven** [comment] 2015-10-01 20:04
Meteor doesn't really have a way to publish beta versions of packages, and I'm not sure I want to release 3.4.0 when it's not final with node-sass (because everyone will upgrade to the beta version not knowing)...

**Comment by juliancwirko** [comment] 2015-10-01 21:15
Ok I understand. So I think this issue should be reopened. 
Packages like https://atmospherejs.com/juliancwirko/zf5 will not work with new build plugin till node-sass 3.4

**Comment by sebakerckhof** [comment] 2015-10-01 21:31
Is it possible to unpublish a version? If so, I think it would be best to unpublish version 3.3.3 until node-sass hits 3.4. Otherwise people will keep running into problems.

**Comment by fourseven** [comment] 2015-10-01 21:37
Last time I checked you couldn't yank packages, the meteor ecosystem is still very basic.

**Comment by brunolemos** [comment] 2015-10-01 21:53
Maybe you could submit the 3.2.0 code as v3.4.0.

**Comment by fourseven** [comment] 2015-10-01 22:51
Here's the link to the yanking issue - https://github.com/meteor/meteor/issues/2459. I'm not sure I want to release a version which doesn't match the underlying node-sass version. @sebakerckhof, do you have any opinions here? You've done the build and support for meteor 1.2 ...

**Comment by sebakerckhof** [comment] 2015-10-02 09:58
Would depend on the release date of the final version of node-sass 3.4, which I do not now.

**Comment by juliancwirko** [comment] 2015-10-02 13:13
Could you relese '3.4.0-beta1' version? I think it is possible with current meteor packages system. So people could decide if they want to use it. Also it shouldn't be autoupdated from 3.3.3 to 3.4.0-beta1

**Comment by fourseven** [comment] 2015-10-03 23:41
@juliancwirko I'm mistaken, I didn't think you could have -beta1 tags on meteor's package system. Turns out you can, and I've published `3.4.0-beta1` for you!

**Comment by juliancwirko** [comment] 2015-10-03 23:43
Cool! :) Many thanks!

**Comment by Vatandeepsingh** [comment] 2015-10-07 07:09
How does this work for importing other packages?
both `@import '{meteoric_ionic-sass}/_ionic';` and `@import '{meteoric:ionic-sass}/_ionic';` dont work for us. I have updated to 3.4.0-beta1

**Comment by sebakerckhof** [comment] 2015-10-07 08:50
Meteoric should update the package for meteor 1.2 and node sass 3.4
