### ISSUE TITLE
icon fonts no longer working

### ISSUE THREAD

**Issue by udnaan** [fourseven/meteor-scss#90] opened 2015-05-22 04:30 UTC
All in all, the issue that I'm facing is very similar to [this](https://github.com/sass/sass/issues/1395). The icon fonts such as font-awesome and material icons work fine with 2.1.1. The latest version(3.1.1) converts the some-icon:before {content: ''} to some illegible character. 

I can't tell whether this is the correct behavior (in the original issue linked above, it seems that this is correct), however it breaks the icons. I already have a mixin similar to what is described in the original issue which doesn't work. 

    @function unicode($str){
	  @return unquote("\"") + $str + unquote("\"");
    }

For now, I don't have time to debug through this and adding the 2.1.1 works. Just leaving this here in case anyone else encounters the same issue. I'll investigate more and add further details once I have time. 

Thanks

**Comment by JulianNorton** [comment] 2015-06-01 18:48
Confirmed. I'm having this same problem.

**Comment by ctaloi** [comment] 2015-06-04 02:49
Same here, let me know if there is any information I can provide to assist in troubleshooting.

**Comment by fongandrew** [comment] 2015-06-15 21:53
Same. I think the issue is related to various designs trying to work around the new behavior (via the unicode mixin) but, for whatever reason, that workaround actually isn't required here anymore. I found removing that removing the mixin and just passing direct ASCII strings seems to work fine though.

That is, if you see something like this:

```
$my-icon: \e8a1;
@function unicode($str){
  @return unquote("\"") + $str + unquote("\"");
}
.prefix-my-icon:before {
  content: unicode($my-icon);
}
```

Just replace with this:
```
$my-icon: '\e8a1';
.prefix-my-icon:before {
  content: $my-icon;
}
```

Note the quote marks around the new `$my-icon` definition.

**Comment by clayne11** [comment] 2015-08-23 19:01
I can confirm what fongandrew@ is saying. Simply using a quoted version of the string fixes the issue. The newer version of Sass does not require the unicode string hack.

**Comment by sebakerckhof** [comment] 2015-10-07 09:04
Okay, by the comments of @fongandrew and @clayne11 I'll close this issue.

**Closed by sebakerckhof** 2015-10-07 09:04 UTC
