### ISSUE TITLE
Issue after last update (materialize:materialize and fourseven:scss)

### ISSUE THREAD

**Issue by lunatolun** [fourseven/meteor-scss#230] opened 2016-11-02 02:08 UTC
It was fine before update. No error logs in to the console.

When I remove and add both packages, the versions seem to be correct:
fourseven:scss           added, version 3.10.0
materialize:materialize  added, version 0.97.8

Errors:

Error: Scss compiler error: Undefined variable: "$medium-and-down"
TypeError: Package['materialize:materialize'] is undefined
ReferenceError: meteorInstall is not defined

**EDIT**
using Materialize 0.97.7 fixed the issue

**Comment by 3210jr** [comment] 2016-11-03 23:57
+1 same problem except using 0.97.7 is not helping

**Comment by bryanlimy** [comment] 2016-11-09 20:08
+1 using 
fourseven:scss 3.10.1
materialize:materialize 0.97.8
gives error:
materialize_materialize.js?hash=97b7fa9…:7826 Uncaught Error: Scss compiler error: Undefined variable: "$medium-and-down".

**Comment by joshuaburkhalter** [comment] 2016-11-12 13:48
+1 same problem here

**Comment by keyscores** [comment] 2016-11-12 20:02
I vote to close this issue. See correct issue here:
https://github.com/Dogfalo/materialize/issues/3905

The issue is with materialize:materialize at version 0.97.8 . The error goes away when downgrading materialize to 0.97.7 , and keeping fouseve:scss at the most updated version.

**Comment by sebakerckhof** [comment] 2017-02-17 18:29
Closed per: https://github.com/Dogfalo/materialize/issues/3905

**Closed by sebakerckhof** 2017-02-17 18:29 UTC
